networkuiapp/ipaddress/views.py
""" IP address views."""

from flask import flash
from flask import url_for
from flask import redirect
from flask import Blueprint
from flask import render_template

from markupsafe import Markup
from networkuiapp import config

from networkuiapp.database import update_pc_count

from networkuiapp.utils import flash_errors
from networkuiapp.utils import make_dropdown
from networkuiapp.utils import make_cidr_range

from networkuiapp.ipaddress.forms import AddForm
from networkuiapp.ipaddress.models import IPAddress
from networkuiapp.networktemplate.models import NetworkTemplate
from networkuiapp.firewall_helpers.firewall_utils import make_json_endpoint

blueprint = Blueprint("ipaddress", __name__, url_prefix="/ipaddress")


@blueprint.route("/add", methods=["GET", "POST"])
def add():
    """Add new ip address"""

    # check if a SSH script is configuring the firewall
    if config.is_a_script_running:
        flash("a script is running please wait before adding a new PC", "danger")
        return redirect(url_for("networktemplates.list"))

    form = AddForm()

    # make the network profile dropdown
    form.network_template.choices = make_dropdown(
        NetworkTemplate, "network_template_name"
    )

    # if the network handicap is empty, ask the user to add one first before adding an ip
    if NetworkTemplate.query.all() == []:
        flash("Add a Network Template first to add an ip address", "warning")
        return redirect(url_for("networktemplates.add"))

    if form.validate_on_submit():

        IPAddress.create(
            ip_address=form.ip_address.data,
            pc_name=form.pc_name.data,
            network_template=form.network_template.data,
        )

        # update the 'no_of_pcs' columns in the Network Templates Table
        update_pc_count(IPAddress, NetworkTemplate, form.network_template.data)

        make_json_endpoint(IPAddress, NetworkTemplate)

        flash(Markup(f"IP address added successfully"), "success")
        return redirect(url_for("public.index"))
    else:
        flash_errors(form)

    # make a dict with template name and cidr limit to show the cidr limit in html page
    # when a template is selected from drop down
    subnets = make_cidr_range(
        NetworkTemplate.query.with_entities(
            NetworkTemplate.network_template_name, NetworkTemplate.cidr_notation
        )
    )
    return render_template("ipaddress/add_ip_address.html", form=form, subnets=subnets)


@blueprint.route("/delete/<int:id>", methods=["GET", "POST"])
def delete(id):
    """Delete an ip address entry"""

    # check if a SSH script is configuring the firewall
    if config.is_a_script_running:
        flash("a script is running please wait before deleting a new PC", "danger")
        return redirect(url_for("networktemplates.list"))

    ip_address_to_delete = IPAddress.query.get(id)
    if ip_address_to_delete:
        IPAddress.delete(ip_address_to_delete)

        # update the 'no_of_pcs' columns in the Network Templates Table
        update_pc_count(
            IPAddress, NetworkTemplate, ip_address_to_delete.network_template
        )

        make_json_endpoint(IPAddress, NetworkTemplate)

        flash(f"IP Address deleted", "success")
    return redirect(url_for("public.index"))


@blueprint.route("/update/<int:id>", methods=["GET", "POST"])
def update(id):
    """Update an ip address"""
    form = AddForm()

    # check if a SSH script is configuring the firewall
    if config.is_a_script_running:
        flash("a script is running please wait before updating a new PC", "danger")
        return redirect(url_for("networktemplates.list"))

    # check if a SSH script is configuring the firewall if not make a config
    else:
        make_json_endpoint(IPAddress, NetworkTemplate)

    # make the network profile dropdown
    form.network_template.choices = make_dropdown(
        NetworkTemplate, "network_template_name"
    )

    # make a dict with template name and cidr limit to show the cidr limit in html page
    # when a template is selected from drop down
    subnets = make_cidr_range(
        NetworkTemplate.query.with_entities(
            NetworkTemplate.network_template_name, NetworkTemplate.cidr_notation
        )
    )

    ip_address_to_update = IPAddress.query.get_or_404(id)

    if form.validate_on_submit():
        old_template_id = ip_address_to_update.network_template

        ip_address_to_update.update(
            pc_name=form.pc_name.data,
            ip_address=form.ip_address.data,
            network_template=form.network_template.data,
        )

        # update the 'no_of_pcs' columns in the Network Templates Table
        update_pc_count(
            IPAddress,
            NetworkTemplate,
            form.network_template.data,
            old_template_id=old_template_id,
        )

        make_json_endpoint(IPAddress, NetworkTemplate)

        flash(Markup(f"IP address updated successfully"), "success")
        return redirect(url_for("public.index"))
    else:
        flash_errors(form)

    return render_template(
        "ipaddress/update_ip_address.html",
        form=form,
        subnets=subnets,
        ip_address_to_update=ip_address_to_update,
    )

networkuiapp/templates/flash.html
{# flash messages #}
{% for category, message in get_flashed_messages(with_categories=true)%}
<div class="alert alert-{{category if category in ['primary', 'danger', 'success', 'warning' ] else 'warning'}} alert-dismissible fade show" role="alert">
    {{message}}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}

networkuiapp/templates/layout.html
<!doctype html>
<html lang="en" class="h-100">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    {% if title %}
    <title>{{title}}</title>
    {%else%}
    <title>Home</title>
    {%endif%}

    <link rel="shortcut icon" href="{{ url_for('static', filename='imgs/favicon.png') }}">
    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" />

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
</head>

<body class="d-flex flex-column h-100">

    <header class="mt-5">
        <!-- Fixed navbar -->
        {# Navbar for all pages #}
        {% include 'nav.html' %}
    </header>




    <!-- Begin page content -->
    <main class="flex-shrink-0">
        <div class="container mt-5 bg-light p-5 rounded mb-5">
            {% include "flash.html" %}
            {# Main page content #}
            <div class="card" style="box-shadow: rgba(149, 157, 165, 0.2) 0px 8px 24px;">
                <div class="card-header">
                    <h3>{{header}}</h3>
                </div>
                <div class="card-body m-3">
                    {% block content %}
                    {% endblock content %}
                </div>
            </div>
        </div>
    </main>





    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.js"></script>

    <!--- https://getbootstrap.com/docs/5.0/components/popovers/#example-enable-popovers-everywhere -->
    <script>
        var popoverTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="popover"]'))
        var popoverList = popoverTriggerList.map(function (popoverTriggerEl) {
            return new bootstrap.Popover(popoverTriggerEl)
        })
    </script>

    <script>
            // JavaScript for disabling form submissions if there are invalid fields
            (() => {
                'use strict'

                // Fetch all the forms we want to apply custom Bootstrap validation styles to
                const forms = document.querySelectorAll('.needs-validation')

                // Loop over them and prevent submission
                Array.from(forms).forEach(form => {
                    form.addEventListener('submit', event => {
                        if (!form.checkValidity()) {
                            event.preventDefault()
                            event.stopPropagation()
                        }

                        form.classList.add('was-validated')
                    }, false)
                })
            })()
    </script>
</body>

</html>

networkuiapp/templates/nav.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <li class="nav-item">
                    <a class="nav-link {% if active_page=='home' %} class= active {% endif %}" aria-current="page" href="{{url_for('public.index')}}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if active_page=='add_ip_address' %} class= active {% endif %}" aria-current="page" href="{{url_for('ipaddress.add')}}">Add IP Address</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if active_page=='add_network_template' %} class= active {% endif %}" aria-current="page" href="{{url_for('networktemplates.add')}}">Add network template</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if active_page=='list_network' %} class= active {% endif %}" aria-current="page" href="{{url_for('networktemplates.list')}}">List all network templates</a>
                </li>
            </ul>
        </div>
    </div>
</nav>