networkuiapp/networkprofile/views.py
""" IP address views."""

from flask import Blueprint
from flask import render_template
from networkuiapp.networkprofile.models import NetworkTemplate
from networkuiapp.networkprofile.forms import AddForm

blueprint = Blueprint("networktemplates", __name__, url_prefix="/networktemplates")


@blueprint.route("/add", methods=["GET", "POST"])
def add():
    form = AddForm()

    if form.validate_on_submit():
        new_network_template = NetworkTemplate.create(
            template_name=form.network_template_name.data,
            cidr_notation=f"{form.cidr_ip.data}/{form.cidr_suffix}",
            bandwidth_restriction_upload=form.bandwidth_restriction_upload.data,
            bandwidth_restriction_download=form.bandwidth_restriction_download.data,
            dns_latency=form.dns_latency.data,
            general_latency=form.general_latency.data,
            packet_loss=form.packet_loss.data,
        )
    return render_template("networkprofile/add_network_template.html", form=form)

networkuiapp/networktemplate/views.py
""" IP address views."""

from flask import flash
from flask import url_for
from flask import redirect
from flask import Blueprint
from markupsafe import Markup
from networkuiapp import config
from flask import render_template
from networkuiapp.utils import flash_errors
from networkuiapp.ipaddress.models import IPAddress
from networkuiapp.networktemplate.forms import AddForm
from networkuiapp.networktemplate.models import NetworkTemplate
from networkuiapp.firewall_helpers.firewall_utils import make_json_endpoint

blueprint = Blueprint("networktemplates", __name__, url_prefix="/networktemplates")


@blueprint.route("/add", methods=["GET", "POST"])
def add():
    """Add a network template"""
    form = AddForm()

    # check if a SSH script is configuring the firewall
    if config.is_a_script_running:
        flash("a script is running please wait before adding a new template", "danger")
        return redirect(url_for("public.index"))

    if form.validate_on_submit():
        cidr_notation = (
            f"{form.cidr_ip.data}/{int(form.cidr_suffix.data)}"
            if form.cidr_ip.data
            else None
        )
        NetworkTemplate.create(
            network_template_name=form.network_template_name.data,
            cidr_notation=cidr_notation,
            bandwidth_restriction_upload=form.bandwidth_restriction_upload.data,
            bandwidth_restriction_download=form.bandwidth_restriction_download.data,
            dns_latency=form.dns_latency.data,
            general_latency=form.general_latency.data,
            packet_loss=form.packet_loss.data,
        )
        make_json_endpoint(IPAddress, NetworkTemplate)
        flash(Markup(f"Network template added successfully"), "success")
        return redirect(url_for("networktemplates.list"))

    else:
        flash_errors(form)
    return render_template("networkprofile/add_network_template.html", form=form)


@blueprint.route("/list", methods=["GET"])
def list():
    """List all network templates"""
    network_templates = NetworkTemplate.query.all()
    return render_template(
        "networkprofile/list_network_template.html", network_templates=network_templates
    )


@blueprint.route("/delete/<int:id>", methods=["GET"])
def delete(id):
    """Delete a network template"""

    # check if a SSH script is configuring the firewall
    if config.is_a_script_running:
        flash(
            "a script is running please wait before deleting a new template", "danger"
        )
        return redirect(url_for("public.index"))

    network_template_to_delete = NetworkTemplate.query.get(id)
    if network_template_to_delete:
        NetworkTemplate.delete(network_template_to_delete)
        make_json_endpoint(IPAddress, NetworkTemplate)
        flash(f"Network Template deleted", "success")
    return redirect(url_for("networktemplates.list"))


@blueprint.route("/update/<int:id>", methods=["GET", "POST"])
def update(id):
    """update a network template"""
    form = AddForm()

    # check if a SSH script is configuring the firewall
    if config.is_a_script_running:
        flash(
            "a script is running please wait before deleting a new template", "danger"
        )
        return redirect(url_for("public.index"))

    network_template_to_update = NetworkTemplate.query.get_or_404(id)

    if form.validate_on_submit():
        cidr_notation = (
            f"{form.cidr_ip.data}/{form.cidr_suffix.data}"
            if form.cidr_ip.data
            else None
        )

        network_template_to_update.update(
            network_template_name=form.network_template_name.data,
            cidr_notation=cidr_notation,
            bandwidth_restriction_upload=form.bandwidth_restriction_upload.data,
            bandwidth_restriction_download=form.bandwidth_restriction_download.data,
            dns_latency=form.dns_latency.data,
            general_latency=form.general_latency.data,
            packet_loss=form.packet_loss.data,
        )
        make_json_endpoint(IPAddress, NetworkTemplate)
        flash("Network Temlate Updated!")
        return redirect(url_for("networktemplates.list"))

    else:
        flash_errors(form)

    return render_template(
        "networkprofile/update_network_template.html",
        form=form,
        network_template_to_update=network_template_to_update,
    )

networkuiapp/templates/networkprofile/add_network_template.html
{% extends "layout.html" %}

{% set active_page = "add_network_template" %}

{% block content %}

<div>
    <h3 class="mb-4">Add a network template</h3>
    <form method="POST" novalidate class="needs-validation row g-3">
        {{form.hidden_tag()}}

        {# Network Template Name field #}
        <div class="mb-2">
            <label for="network_template_name" class="form-label">{{form.network_template_name.label}}</label>
            {{form.network_template_name(class="form-control", required="required", id="network_template_name", placeholder="Good Network")}}
            <div class="valid-feedback">Looks good!</div>
            <div class="invalid-feedback">Please enter a name for Network Template.</div>
        </div>

        {# Bandwidth Restriction Upload field #}
        <div class="mb-2">
            <label for="bandwidth_restriction_upload" class="form-label">{{form.bandwidth_restriction_upload.label}}</label>
            {{form.bandwidth_restriction_upload(class="form-control", type="number", min=0, step="0.01", id="bandwidth_restriction_upload")}}
            <div class="valid-feedback">Looks good!</div>
            <div class="invalid-feedback">Stop QA'ing and enter a NUMBER.</div>
        </div>

        {# Bandwidth Restriction Download field #}
        <div class="mb-2">
            <label for="bandwidth_restriction_download" class="form-label">{{form.bandwidth_restriction_download.label}}</label>
            {{form.bandwidth_restriction_download(class="form-control", type="number", min=0, step="0.01", id="bandwidth_restriction_download")}}
            <div class="valid-feedback">Looks good!</div>
            <div class="invalid-feedback">Stop QA'ing and enter a NUMBER.</div>
        </div>

        {# DNS Latency field #}
        <div class="mb-2">
            <label for="dns_latency" class="form-label">{{form.dns_latency.label}}</label>
            {{form.dns_latency(class="form-control", type="number", min=0, step="0.1", id="dns_latency")}}
            <div class="valid-feedback">Looks good!</div>
            <div class="invalid-feedback">Stop QA'ing and enter a NUMBER.</div>
        </div>

        {# General Latency field #}
        <div class="mb-2">
            <label for="general_latency" class="form-label">{{form.general_latency.label}}</label>
            {{form.general_latency(class="form-control", type="number", min=0, step="0.1", id="general_latency")}}
            <div class="valid-feedback">Looks good!</div>
            <div class="invalid-feedback">Stop QA'ing and enter a NUMBER.</div>
        </div>

        {# Packet Loss field #}
        <div class="mb-2">
            <label for="packet_loss" class="form-label">{{form.packet_loss.label}}</label>
            {{form.packet_loss(class="form-control", type="number", min=0, step="0.1", id="packet_loss", value=0, placeholder="default value 0")}}
            <div class="valid-feedback">Looks good!</div>
            <div class="invalid-feedback">Stop QA'ing and enter a NUMBER.</div>
        </div>


        {# Subnet #}
        {# Subnet IP #}
        <div class="col-md-6">
            <label for="cidr_ip" class="form-label">{{form.cidr_ip.label}}</label>
            {{form.cidr_ip(class="form-control", id="cidr_ip", placeholder="192.168.1.1 (optional)")}}
            <div class="valid-feedback">Looks good!</div>
            <div class="invalid-feedback">Stop QA'ing and enter a valid IP address.</div>
        </div>

        {# Subnet Suffix #}
        <div class="col-md-2">
            <label for="cidr_suffix" class="form-label">{{form.cidr_suffix.label}}</label>
            {{form.cidr_suffix(class="form-control", type="number", min=0, max=32, placeholder="30 (optional)")}}
            <div class="valid-feedback">Looks good!</div>
            <div class="invalid-feedback">Enter a valid number between 0 - 32</div>
        </div>

        {# submit button #}
        <div class="md-5">
            {{form.submit(class="btn btn-outline-primary")}}
        </div>
    </form>
</div>

{% endblock content %}

networkuiapp/templates/networkprofile/list_network_template.html
{% extends "layout.html" %}

{% set active_page = "list_network" %}
{% set title = "All network templates" %}
{% set header = "List of network templates" if network_templates else "No Network templates added yet" %}

{% block content %}

<div>
    {% if network_templates %}
    <div class="table-responsive">
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Template Name <div style="font-weight: normal; font-size: small;">SubNet mask</div>
                    </th>
                    <th scope="col">Bandwidth restriction (max upload, max download)</th>
                    <th scope="col">DNS Latency</th>
                    <th scope="col">General Latency</th>
                    <th scope="col">Packet Loss %</th>
                    <th scope="col">Number of PCs</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            {% for network_template in network_templates %}
            <tbody>
                <th scope="row">{{loop.index}}</th>
                <td><b>{{network_template.network_template_name}}</b><br>
                    {% if network_template.cidr_notation %}
                    <div style="font-size: small;">{{network_template.cidr_notation}}</div>
                    {% endif %}
                </td>
                <td>{{network_template.bandwidth_restriction_upload ~ ' MB, ' if network_template.bandwidth_restriction_upload
                    is not none else '--,'}} {{network_template.bandwidth_restriction_download ~ ' MB, ' if
                    network_template.bandwidth_restriction_download is not none else '--'}}
                </td>
                <td>{{network_template.dns_latency if network_template.dns_latency is not none else '--'}}</td>
                <td>{{network_template.general_latency if network_template.general_latency is not none else '--'}}</td>
                <td>{{network_template.packet_loss if network_template.packet_loss is not none else '--'}}</td>
                <td>{{network_template.no_of_pcs}}</td>
                <td>
                    <div style="width: max-content;">
                        <button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#deleteTemplateConfirm{{network_template.id}}">
                            Delete
                        </button>
                        <!-- Modal -->
                        <div class="modal fade" id="deleteTemplateConfirm{{network_template.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog modal-dialog-centered">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h1 class="modal-title fs-5" id="exampleModalLabel">Delete
                                            <b>{{network_template.network_template_name}}?</b>
                                        </h1>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        Are you sure you wanted to delete "{{network_template.network_template_name}}?"
                                        {% if network_template.no_of_pcs | int > 1 %} <u>This is going to affect
                                            {{network_template.no_of_pcs}} devices</u>
                                        {% elif network_template.no_of_pcs | int == 1 %}
                                        <u>This is going to affect {{network_template.no_of_pcs}} device</u>
                                        {% else %}
                                        {% endif %}
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                        <a href="{{ url_for('networktemplates.delete', id=network_template.id) }}" type="button" class="btn btn-danger">Delete, I fear no
                                            man</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <a class="btn btn-outline-warning" href="{{ url_for('networktemplates.update', id=network_template.id) }}">Edit</a>
                    </div>
                </td>
            </tbody>
            {% endfor %}
        </table>
    </div>
    {% endif %}
</div>
{% endblock content %}

networkuiapp/templates/networkprofile/update_network_template.html
{% extends "layout.html" %}

{% set title = "Update " + network_template_to_update.network_template_name %}

{% set header %}
Update <b>{{network_template_to_update.network_template_name}}</b>
{% endset %}

{% block content %}

<div>
    <form method="POST" novalidate class="needs-validation row g-3">
        {{form.hidden_tag()}}

        {# a hidden field to send the selected ID to the form to validate while updating the entries #}
        <input value="{{request.view_args['id']}}" type="hidden" name="update_id">

        {# Network Template Name field #}
        <div class="mb-2">
            <label for="network_template_name" class="form-label">{{form.network_template_name.label}}</label>
            {{form.network_template_name(value=network_template_to_update.network_template_name,class="form-control", required="required", id="network_template_name", placeholder="Good Network")}}
            <div class="valid-feedback">Looks good!</div>
            <div class="invalid-feedback">Please enter a name for Network Template.</div>
        </div>

        {# Bandwidth Restriction Upload field #}
        <div class="mb-2">
            <label for="bandwidth_restriction_upload" class="form-label">{{form.bandwidth_restriction_upload.label}}</label>
            {{form.bandwidth_restriction_upload(value=network_template_to_update.bandwidth_restriction_upload,class="form-control", type="number", min=0, step="0.01", id="bandwidth_restriction_upload")}}
            <div class="valid-feedback">Looks good!</div>
            <div class="invalid-feedback">Stop QA'ing and enter a NUMBER.</div>
        </div>

        {# Bandwidth Restriction Download field #}
        <div class="mb-2">
            <label for="bandwidth_restriction_download" class="form-label">{{form.bandwidth_restriction_download.label}}</label>
            {{form.bandwidth_restriction_download(value=network_template_to_update.bandwidth_restriction_download,class="form-control", type="number", min=0, step="0.01", id="bandwidth_restriction_download")}}
            <div class="valid-feedback">Looks good!</div>
            <div class="invalid-feedback">Stop QA'ing and enter a NUMBER.</div>
        </div>

        {# DNS Latency field #}
        <div class="mb-2">
            <label for="dns_latency" class="form-label">{{form.dns_latency.label}}</label>
            {{form.dns_latency(value=network_template_to_update.dns_latency,class="form-control", type="number", min=0, step="0.1", id="dns_latency")}}
            <div class="valid-feedback">Looks good!</div>
            <div class="invalid-feedback">Stop QA'ing and enter a NUMBER.</div>
        </div>

        {# General Latency field #}
        <div class="mb-2">
            <label for="general_latency" class="form-label">{{form.general_latency.label}}</label>
            {{form.general_latency(value=network_template_to_update.general_latency,class="form-control", type="number", min=0, step="0.1", id="general_latency")}}
            <div class="valid-feedback">Looks good!</div>
            <div class="invalid-feedback">Stop QA'ing and enter a NUMBER.</div>
        </div>

        {# Packet Loss field #}
        <div class="mb-2">
            <label for="packet_loss" class="form-label">{{form.packet_loss.label}}</label>
            {{form.packet_loss(value=network_template_to_update.packet_loss,class="form-control", type="number", min=0, step="0.1", id="packet_loss", value=0, placeholder="default value 0")}}
            <div class="valid-feedback">Looks good!</div>
            <div class="invalid-feedback">Stop QA'ing and enter a NUMBER.</div>
        </div>
        {{network_template_to_update.cidr_ip}}

        {# Subnet #}
        {# Subnet IP #}
        <div class="col-md-6">
            <label for="cidr_ip" class="form-label">{{form.cidr_ip.label}}</label>
            {{form.cidr_ip(value=network_template_to_update.cidr_notation.split('/')[0] if network_template_to_update.cidr_notation,class="form-control", id="cidr_ip", placeholder="192.168.1.1 (optional)")}}
            <div class="valid-feedback">Looks good!</div>
            <div class="invalid-feedback">Stop QA'ing and enter a valid IP address.</div>
        </div>

        {# Subnet Suffix #}
        <div class="col-md-2">
            <label for="cidr_suffix" class="form-label">{{form.cidr_suffix.label}}</label>
            {{form.cidr_suffix(value=network_template_to_update.cidr_notation.split('/')[1] if network_template_to_update.cidr_notation,class="form-control", type="number", min=0, max=32, placeholder="30 (optional)")}}
            <div class="valid-feedback">Looks good!</div>
            <div class="invalid-feedback">Enter a valid number between 0 - 32</div>
        </div>

        {# submit button #}
        <div class="md-5">
            {{form.submit(class="btn btn-outline-primary", value="Update")}}
            <a class="btn btn-outline-secondary" href="{{ url_for('networktemplates.list')}}">Cancel</a>
        </div>
    </form>
</div>

{% endblock content %}